package gui;

import models.Item;
import models.ShoppingList;
import database_helpers.DatabaseHelper;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;

public class UI extends javax.swing.JFrame {
    
    private Item newItem;
    private DatabaseHelper dbh;
    private ShoppingList list1;
    
    private DefaultListModel model;
    private DefaultListModel pmodel;

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        jPopupMenu1.add(jLabel1);
        jPopupMenu1.add(jTextField1);
        jPopupMenu1.add(jLabel2);
        jPopupMenu1.add(jTextField2);
        jPopupMenu1.add(jLabel3);
        jPopupMenu1.add(jTextField3);
        jPopupMenu1.add(jLabel4);
        jPopupMenu1.add(jTextField4);
        jPopupMenu1.add(jCheckBox1);
        jPopupMenu1.add(jButtonPopupHinzufügen);
        list1 = new ShoppingList("", "Wocheneinkauf");
        
        // Automatically connects to db
        String url = "jdbc:sqlite:src\\saves\\Main.db";
        Connection conn = null;
        // Set up connection
        try{
            conn = DriverManager.getConnection(url);
        } catch (SQLException e){
            System.out.println(e.getMessage());
        }
        dbh = new DatabaseHelper(conn);
        
         //print Shoppinglist  
        model = new DefaultListModel();
        pmodel = new DefaultListModel();
        
        /*model.addElement("Zucker");
        model.addElement("Mehl");
        model.addElement("Salz");
        
        pmodel.addElement("Milch");*/
        
        jTextFieldShoppingListName.setText(list1.getName());
                
        
       //print all items at the beginning
        jShoppingList.setModel(model);
        System.out.println("all items at the beginning");
        //System.out.println(list1 + "Liste vor addItem");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButtonPopupHinzufügen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckPriority = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jShoppingList = new javax.swing.JList<>();
        jTextFieldShoppingListName = new javax.swing.JTextField();

        jLabel1.setText("Produktname");

        jTextField1.setText(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setText("Kategorie");

        jTextField2.setText(null);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jCheckBox1.setText("Priorität");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Anzahl");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jButtonPopupHinzufügen.setText("Hinzufügen");
        jButtonPopupHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPopupHinzufügenActionPerformed(evt);
            }
        });

        jLabel4.setText("Preis");

        jTextField4.setText("");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckPriority.setText("Priority");
        jCheckPriority.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckPriorityMouseClicked(evt);
            }
        });

        jShoppingList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jShoppingList);

        jTextFieldShoppingListName.setText("Hier könnte der Name Ihrer ShoppingList stehen :)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckPriority)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldShoppingListName, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckPriority)
                    .addComponent(jTextFieldShoppingListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newItem = new Item(null, null, null, null, null, 0, 0);
        System.out.println(newItem.toString() + " jButton1 pressed");
        jPopupMenu1.show(jButton1, -jButton1.getWidth(), -jButton1.getHeight()*2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //System.out.println("Text Field 1 Enter Pressed");
            System.out.println(jTextField1.getText());
            newItem.setName(jTextField1.getText());
            System.out.println(newItem.toString());
            }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButtonPopupHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPopupHinzufügenActionPerformed
        newItem.setName(jTextField1.getText());
        newItem.setCategory(jTextField2.getText());
        newItem.setAmount(jTextField3.getText());
        newItem.setPrice(jTextField4.getText());
        
        if(jTextField1.getText() != null && jTextField2.getText() != null && jTextField2.getText() != null){
            System.out.println("New Item: " + newItem.toString());
            System.out.println("Inhalt Liste: " + list1.toString());
            
            if(jCheckBox1.isSelected()){
                pmodel.addElement(newItem);
            }
            model.addElement(newItem);
        }
        dbh.addItem("1", jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jTextField4.getText(), newItem.getPriority());
        jPopupMenu1.setVisible(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
    }//GEN-LAST:event_jButtonPopupHinzufügenActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //System.out.println("Text Field 2 Enter Pressed");
            System.out.println(jTextField2.getText());
            newItem.setCategory(jTextField2.getText());
            System.out.println(newItem.toString());
            }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()) {
            newItem.setPriority(1);
            System.out.println("Checkbox selected " + newItem.getPriority());
            System.out.println(newItem.toString());
        } else {
            newItem.setPriority(0);
            System.out.println(newItem.toString());
        }   
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //System.out.println("Text Field 3 Enter Pressed");
            System.out.println(jTextField3.getText());
            newItem.setAmount(jTextField3.getText());
            System.out.println(newItem.toString());
            }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jCheckPriorityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckPriorityMouseClicked
        //print only items with priority
        if(jCheckPriority.isSelected()){
        jShoppingList.setModel(pmodel);
            System.out.println("only items with priority");
        }else{
            jShoppingList.setModel(model);
            System.out.println("all items");            
        }

    }//GEN-LAST:event_jCheckPriorityMouseClicked

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //System.out.println("Text Field 4 Enter Pressed");
            System.out.println(jTextField4.getText());
            newItem.setPrice(jTextField4.getText());
            System.out.println(newItem.toString());
            }
    }//GEN-LAST:event_jTextField4KeyPressed
                                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPopupHinzufügen;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckPriority;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jShoppingList;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldShoppingListName;
    // End of variables declaration//GEN-END:variables
}
